Fix tmux display for other possible TERMs
ranger/ranger pull request #2347
Opened 2021-06-04 21:21 UTC by Barbarossa93

This fixes what TERMs are checked in relation to a tmux session and then apply the correct escape sequences for the URxvt and iterm backends
#### ISSUE TYPE

- Bug fix

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux
- Terminal emulator and version: rxvt-unicode 9.26
- Python version: 3.9.5
- Ranger version/commit: 
- Locale: UTF-8

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [ ] Changes require config files to be updated
    - [ ] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

Previously, only the TERM value of `screen` was checked when performing image previews inside of tmux. This PR expands the possible values checked to include all(?) tmux TERM values.

#### MOTIVATION AND CONTEXT

My image previews weren't working with the urxvt backend inside of tmux :(

The image previews work inside of tmux now!

#### TESTING

No tests run to be honest. This shouldn't impact anything, it's a pretty minor change.

#### IMAGES / VIDEOS

2021-06-04 21:44 UTC, toonn commented on ranger/ext/img_display.py
> +        if any(x in os.environ['TERM'] for x in ["screen", "screen-256color", "tmux", "tmux-256color"]):
Since we're using `in` we can just check for the "screen" and "tmux" substrings.

2021-06-04 21:45 UTC, toonn requested changes
Let's check the substrings are prefixes instead.

2021-06-04 21:48 UTC, toonn commented on ranger/ext/img_display.py
> +        if any(x in os.environ['TERM'] for x in ["screen", "screen-256color", "tmux", "tmux-256color"]):
Replace the `any(...)` with `os.environ["TERM"].startswith(("screen", "tmux"))`

2021-06-04 21:50 UTC, Barbarossa93 commented
I believe that should do it? Sorry, I know very little python

2021-06-04 21:57 UTC, toonn reviewed
LGTM I'll look at merging this tomorrow.

You did test your most recent change, right?

2021-06-04 22:02 UTC, toonn commented
Squashing's fine, yeah.

2021-06-04 22:10 UTC, Barbarossa93 commented
There we go, should be all set!

2021-06-08 10:15 UTC, toonn approved these changes
LGTM

2021-06-08 10:16 UTC, merged

2021-06-08 10:16 UTC, toonn commented
Great first contribution! : )