Acknowledge and report the exit status of the rifle'd commands
ranger/ranger pull request #2574
Opened 2022-02-21 12:57 UTC by vifon

#### ISSUE TYPE

- Improvement/feature implementation

#### CHECKLIST

- [X] The `CONTRIBUTING` document has been read **[REQUIRED]**
- [X] All changes follow the code style **[REQUIRED]**
- [X] All new and existing tests pass **[REQUIRED]**
- [ ] Changes require config files to be updated
    - [ ] Config files have been updated
- [ ] Changes require documentation to be updated
    - [ ] Documentation has been updated
- [ ] Changes require tests to be updated
    - [ ] Tests have been updated

#### DESCRIPTION

Currently `rifle` completely ignores the exit status of the commands it runs, even if it does wait for them (it's obviously not viable otherwise). This patch makes `rifle(1)` (the commandline application) exit with the same status the command did, and makes `rifle` the module raise `subprocess.CalledProcessError`, so it's displayed in the `ranger` status line.

#### MOTIVATION AND CONTEXT

As it stands, it was impossible to inspect whether the commands executed by `rifle` were successful or not.

#### TESTING

The errors are no longer swallowed and instead are reported back in the manner described above. If someone relied on them being swallowed, it might break their use case (but maybe for the better).

2022-02-21 13:01 UTC, toonn reviewed
LGTM

Ranger still swallows these unless run with `--debug`, right?

2022-02-21 14:29 UTC, vifon commented
It swallows them loudly: with the red text in the notification area.

2022-02-27 12:33 UTC, toonn approved these changes
Tested and working.

Maybe we can render the list as a single string? If it's not too much effort. I think that'd be slightly easier for debugging because you could then simply copy the string to a terminal and go from there.

2022-06-20 14:33 UTC, toonn requested changes
How about that improved error message? ; )

2022-06-21 11:52 UTC, vifon commented
Sorry for the delay. I still remember about it, I just need to get around to this.

2022-11-17 12:52 UTC, toonn reviewed
I think this is all we'd need? Feel free to either batch and apply the suggestions or to simply confirm and I'll do it locally : )

2022-11-17 12:52 UTC, toonn commented on ranger/ext/rifle.py
> +from subprocess import PIPE, CalledProcessError
```suggestion
import shlex
from subprocess import PIPE, CalledProcessError
```

2022-11-17 12:52 UTC, toonn commented on ranger/ext/rifle.py
> +                            raise CalledProcessError(exit_code, cmd)
```suggestion
                            raise CalledProcessError(exit_code, shlex.join(cmd))
```

2022-11-18 11:00 UTC, toonn approved these changes
LGTM

2022-11-18 11:05 UTC, merged